[
  {
    permissionId: 0,
    waRoleId: 1,
    actions: [
      {
        waRoleId: 1,
        name: "VIEW DASHBOARD",
        roleIsActive: true,
        modulePage: "Dashboard",
        actionId: 1,
        action: "view-dashboard",
      },
      {
        waRoleId: 1,
        name: "VIEW REQUEST MANAGEMENT",
        roleIsActive: true,
        modulePage: "Request Management",
        actionId: 2,
        action: "view-request-management",
      },
      {
        waRoleId: 1,
        name: "VIEW PENDING REQUEST",
        roleIsActive: true,
        modulePage: "Request Management",
        actionId: 3,
        action: "view-pending-request",
      },
      {
        waRoleId: 1,
        name: "EDIT MERCHANT IN PENDING",
        roleIsActive: true,
        modulePage: "Request Management",
        actionId: 4,
        action: "edit-merchant-in-pending",
      },
      {
        waRoleId: 1,
        name: "REJECT MERCHANT IN PENDING",
        roleIsActive: true,
        modulePage: "Request Management",
        actionId: 5,
        action: "reject-merchant-in-pending",
      },
      {
        waRoleId: 1,
        name: "ACCEPT MERCHANT IN PENDING",
        roleIsActive: true,
        modulePage: "Request Management",
        actionId: 6,
        action: "accept-merchant-in-pending",
      },
      {
        waRoleId: 1,
        name: "VIEW APPROVED REQUEST",
        roleIsActive: true,
        modulePage: "Request Management",
        actionId: 7,
        action: "view-approved-request",
      },
      {
        waRoleId: 1,
        name: "VIEW REJECTED REQUEST",
        roleIsActive: true,
        modulePage: "Request Management",
        actionId: 8,
        action: "view-rejected-request",
      },
      {
        waRoleId: 1,
        name: "EDIT MERCHANT IN REJECTED REQUEST",
        roleIsActive: true,
        modulePage: "Request Management",
        actionId: 9,
        action: "edit-merchant-in-rejected-request",
      },
      {
        waRoleId: 1,
        name: "REVERT MERCHANT IN REJECTED REQUEST",
        roleIsActive: true,
        modulePage: "Request Management",
        actionId: 10,
        action: "revert-merchant-in-rejected-request",
      },

      {
        waRoleId: 1,
        name: "VIEW MERCHANT LIST",
        roleIsActive: true,
        modulePage: "Merchant",
        actionId: 11,
        action: "view-merchant-list",
      },
      {
        waRoleId: 1,
        name: "EXPORT SETTLEMENT",
        roleIsActive: true,
        modulePage: "Merchant",
        actionId: 12,
        action: "export-settlement",
      },
      {
        waRoleId: 1,
        name: "EDIT MERCHANT",
        roleIsActive: true,
        modulePage: "Merchant",
        actionId: 13,
        action: "edit-merchant",
      },
      {
        waRoleId: 1,
        name: "ADD NEW STAFF",
        roleIsActive: true,
        modulePage: "Merchant",
        actionId: 14,
        action: "add-new-staff",
      },
      {
        waRoleId: 1,
        name: "SET ACTIVE/INACTIVE STAFF",
        roleIsActive: true,
        modulePage: "Merchant",
        actionId: 15,
        action: "active-staff",
      },
      {
        waRoleId: 1,
        name: "EDIT STAFF",
        roleIsActive: true,
        modulePage: "Merchant",
        actionId: 16,
        action: "edit-staff",
      },
      {
        waRoleId: 1,
        name: "ADD NEW CATEGORY",
        roleIsActive: true,
        modulePage: "Merchant",
        actionId: 17,
        action: "add-new-category",
      },
      {
        waRoleId: 1,
        name: "SET ACTIVE/INACTIVE CATEGORY",
        roleIsActive: true,
        modulePage: "Merchant",
        actionId: 18,
        action: "active-category",
      },
      {
        waRoleId: 1,
        name: "EDIT CATEGORY",
        roleIsActive: true,
        modulePage: "Merchant",
        actionId: 19,
        action: "edit-category",
      },
      {
        waRoleId: 1,
        name: "ADD NEW SERVICE",
        roleIsActive: true,
        modulePage: "Merchant",
        actionId: 20,
        action: "add-new-service",
      },
      {
        waRoleId: 1,
        name: "SET ACTIVE/INACTIVE SERVICE",
        roleIsActive: true,
        modulePage: "Merchant",
        actionId: 21,
        action: "active-service",
      },
      {
        waRoleId: 1,
        name: "EDIT SERVICE",
        roleIsActive: true,
        modulePage: "Merchant",
        actionId: 22,
        action: "edit-service",
      },
      {
        waRoleId: 1,
        name: "ADD NEW PRODUCT",
        roleIsActive: true,
        modulePage: "Merchant",
        actionId: 23,
        action: "add-new-product",
      },
      {
        waRoleId: 1,
        name: "SET ACTIVE/INACTIVE PRODUCT",
        roleIsActive: true,
        modulePage: "Merchant",
        actionId: 24,
        action: "active-product",
      },
      {
        waRoleId: 1,
        name: "EDIT PRODUCT",
        roleIsActive: true,
        modulePage: "Merchant",
        actionId: 25,
        action: "edit-product",
      },
      {
        waRoleId: 1,
        name: "SET ACTIVE/INACTIVE EXTRA",
        roleIsActive: true,
        modulePage: "Merchant",
        actionId: 26,
        action: "active-extra",
      },
      {
        waRoleId: 1,
        name: "EDIT EXTRA",
        roleIsActive: true,
        modulePage: "Merchant",
        actionId: 27,
        action: "edit-extra",
      },
      {
        waRoleId: 1,
        name: "EDIT SETTING",
        roleIsActive: true,
        modulePage: "Merchant",
        actionId: 28,
        action: "edit-setting",
      },
      {
        waRoleId: 1,
        name: "SET ACTIVE/INACTIVE MERCHANT",
        roleIsActive: true,
        modulePage: "Merchant",
        actionId: 29,
        action: "active-merchant",
      },

      {
        waRoleId: 1,
        name: "VIEW CONSUMER LIST",
        roleIsActive: true,
        modulePage: "Consumer",
        actionId: 30,
        action: "view-consumer-list",
      },
      {
        waRoleId: 1,
        name: "EDIT CONSUMER",
        roleIsActive: true,
        modulePage: "Consumer",
        actionId: 31,
        action: "edit-consumer",
      },
      {
        waRoleId: 1,
        name: "VIEW CONSUMER TRANSACTIONS",
        roleIsActive: true,
        modulePage: "Consumer",
        actionId: 32,
        action: "view-consumer-transactions",
      },

      {
        waRoleId: 1,
        name: "VIEW GIFT CARD",
        roleIsActive: true,
        modulePage: "Gift Card",
        actionId: 33,
        action: "view-gift-card",
      },
      {
        waRoleId: 1,
        name: "VIEW GENERATION",
        roleIsActive: true,
        modulePage: "Gift Card",
        actionId: 34,
        action: "view-generation",
      },
      {
        waRoleId: 1,
        name: "ADD NEW GIFT CARD",
        roleIsActive: true,
        modulePage: "Gift Card",
        actionId: 35,
        action: "add-new-gift-card",
      },
      {
        waRoleId: 1,
        name: "DELETE GIFT CARD",
        roleIsActive: true,
        modulePage: "Gift Card",
        actionId: 36,
        action: "delete-gift-card",
      },
      {
        waRoleId: 1,
        name: "EDIT GIFT CARD",
        roleIsActive: true,
        modulePage: "Gift Card",
        actionId: 37,
        action: "edit-gift-card",
      },
      {
        waRoleId: 1,
        name: "ADD GIFT CARD CODE",
        roleIsActive: true,
        modulePage: "Gift Card",
        actionId: 38,
        action: "add-gift-card-code",
      },
      {
        waRoleId: 1,
        name: "VIEW CODES",
        roleIsActive: true,
        modulePage: "Gift Card",
        actionId: 39,
        action: "view-codes",
      },
      {
        waRoleId: 1,
        name: "VIEW TEMPLATE",
        roleIsActive: true,
        modulePage: "Gift Card",
        actionId: 40,
        action: "view-template",
      },
      {
        waRoleId: 1,
        name: "ADD NEW TEMPLATE",
        roleIsActive: true,
        modulePage: "Gift Card",
        actionId: 41,
        action: "add-new-template",
      },
      {
        waRoleId: 1,
        name: "SET ACTIVE/INACTIVE TEMPLATE",
        roleIsActive: true,
        modulePage: "Gift Card",
        actionId: 42,
        action: "active-template",
      },
      {
        waRoleId: 1,
        name: "EDIT TEMPLATE",
        roleIsActive: true,
        modulePage: "Gift Card",
        actionId: 43,
        action: "edit-template",
      },

      {
        waRoleId: 1,
        name: "VIEW PRICING PLANE",
        roleIsActive: true,
        modulePage: "Pricing Plan",
        actionId: 44,
        action: "view-pricing-plan",
      },
      {
        waRoleId: 1,
        name: "VIEW ACCOUNTS",
        roleIsActive: true,
        modulePage: "Accounts",
        actionId: 45,
        action: "view-accounts",
      },
      {
        waRoleId: 1,
        name: "VIEW USER",
        roleIsActive: true,
        modulePage: "Accounts",
        actionId: 46,
        action: "view-user",
      },
      {
        waRoleId: 1,
        name: "ADD NEW USER",
        roleIsActive: true,
        modulePage: "Accounts",
        actionId: 47,
        action: "add-new-user",
      },
      {
        waRoleId: 1,
        name: "SET ACTIVE/INACTIVE USER",
        roleIsActive: true,
        modulePage: "Accounts",
        actionId: 48,
        action: "active-user",
      },
      {
        waRoleId: 1,
        name: "EDIT USER",
        roleIsActive: true,
        modulePage: "Accounts",
        actionId: 49,
        action: "edit-user",
      },
      {
        waRoleId: 1,
        name: "VIEW ROLE",
        roleIsActive: true,
        modulePage: "Accounts",
        actionId: 50,
        action: "view-role",
      },
      {
        waRoleId: 1,
        name: "EDIT ROLE",
        roleIsActive: true,
        modulePage: "Accounts",
        actionId: 51,
        action: "edit-role",
      },
      {
        waRoleId: 1,
        name: "VIEW LOGS",
        roleIsActive: true,
        modulePage: "Accounts",
        actionId: 52,
        action: "view-log",
      },
      {
        waRoleId: 1,
        name: "VIEW REPORTS",
        roleIsActive: true,
        modulePage: "Reports",
        actionId: 53,
        action: "view-reports",
      },
      {
        waRoleId: 1,
        name: "VIEW TRANSACTIONS",
        roleIsActive: true,
        modulePage: "Reports",
        actionId: 54,
        action: "view-transactions",
      },
      {
        waRoleId: 1,
        name: "VIEW GIFT CARD TRANSACTIONS",
        roleIsActive: true,
        modulePage: "Reports",
        actionId: 55,
        action: "view-gift-card-transactions",
      },
      {
        waRoleId: 1,
        name: "VIEW MERCHANT BATCH SETTLEMENT",
        roleIsActive: true,
        modulePage: "Reports",
        actionId: 56,
        action: "view-merchant-batch-settlement",
      },
    ],
  },
];
