//GET ALL ACCEPTED MERCHANT LIST
export const getAll_Merchants = 'getAll_Merchants'
export const getAll_Merchants_Success = 'getAll_Merchants_Success'
export const getAll_Merchants_Error = 'getAll_Merchants_Error'
export const SearchMerchants = 'SearchMerchants';
export const ViewProfile_Merchants = 'ViewProfile_Merchants';
// GET PENDING MERCHANT LIST 
export const getAll_Merchant_Requests = 'getAll_Merchant_Requests'
export const getAll_Merchant_Requests_Success = 'getAll_Merchant_Requests_Success'
export const getAll_Merchant_Requests_Error = 'getAll_Merchant_Requests_Error'
export const SearchMerchant_Request = 'SearchMerchant_Request';
export const ViewMerchant_Request = 'ViewMerchant_Request';
// GET REJECTED MERCHANT LIST 
export const getAll_Rejected_Merchants = 'getAll_Rejected_Merchants'
export const getAll_Rejected_Merchants_Success = 'getAll_Rejected_Merchants_Success'
export const getAll_Rejected_Merchants_Error = 'getAll_Rejected_Merchants_Error'
export const ViewMerchant_Rejected_Merchants = 'ViewMerchant_Rejected_Merchants';