export const GET_CONSUMER_BY_ID_REQUEST = "GET_CONSUMER_BY_ID_REQUEST";
export const GET_CONSUMER_BY_ID_SUCCESS = "GET_CONSUMER_BY_ID_SUCCESS";
export const GET_CONSUMER_BY_ID_FAILURE = "GET_CONSUMER_BY_ID_FAILURE";

export const VIEW_CONSUMER = "VIEW_CONSUMER";

export const ARCHIVE_CONSUMER_BY_ID_REQUEST = "ARCHIVE_CONSUMER_BY_ID_REQUEST";
export const ARCHIVE_CONSUMER_BY_ID_SUCCESS = "ARCHIVE_CONSUMER_BY_ID_SUCCESS";
export const ARCHIVE_CONSUMER_BY_ID_FAILURE = "ARCHIVE_CONSUMER_BY_ID_FAILURE";

export const RESTORE_CONSUMER_BY_ID_REQUEST = "RESTORE_CONSUMER_BY_ID_REQUEST";
export const RESTORE_CONSUMER_BY_ID_SUCCESS = "RESTORE_CONSUMER_BY_ID_SUCCESS";
export const RESTORE_CONSUMER_BY_ID_FAILURE = "RESTORE_CONSUMER_BY_ID_FAILURE";

export const UPDATE_CONSUMER_REQUEST = "UPDATE_CONSUMER_REQUEST";
export const UPDATE_CONSUMER_SUCCESS = "UPDATE_CONSUMER_SUCCESS";
export const UPDATE_CONSUMER_FAILURE = "UPDATE_CONSUMER_FAILURE";
