export const GET_GIFT_CARD_GENERAL_BY_ID_REQUEST =
  "GET_GIFT_CARD_GENERAL_BY_ID_REQUEST";
export const GET_GIFT_CARD_GENERAL_BY_ID_SUCCESS =
  "GET_GIFT_CARD_GENERAL_BY_ID_SUCCESS";
export const GET_GIFT_CARD_GENERAL_BY_ID_FAILURE =
  "GET_GIFT_CARD_GENERAL_BY_ID_FAILURE";

export const ADD_GIFT_CARD_GENERAL_CODE_REQUEST =
  "ADD_GIFT_CARD_GENERAL_CODE_REQUEST";
export const ADD_GIFT_CARD_GENERAL_CODE_SUCCESS =
  "ADD_GIFT_CARD_GENERAL_CODE_SUCCESS";
export const ADD_GIFT_CARD_GENERAL_CODE_FAILURE =
  "ADD_GIFT_CARD_GENERAL_CODE_FAILURE";

export const VIEW_GIFT_CARD_GENERAL = "VIEW_GIFT_CARD_GENERAL";
