export const GET_GIFT_CARD_GENERAL_BY_ID_REQUEST =
  "GET_GIFT_CARD_GENERAL_BY_ID_REQUEST";
export const GET_GIFT_CARD_GENERAL_BY_ID_SUCCESS =
  "GET_GIFT_CARD_GENERAL_BY_ID_SUCCESS";
export const GET_GIFT_CARD_GENERAL_BY_ID_FAILURE =
  "GET_GIFT_CARD_GENERAL_BY_ID_FAILURE";

export const ADD_GIFT_CARD_GENERAL_CODE_REQUEST =
  "ADD_GIFT_CARD_GENERAL_CODE_REQUEST";
export const ADD_GIFT_CARD_GENERAL_CODE_SUCCESS =
  "ADD_GIFT_CARD_GENERAL_CODE_SUCCESS";
export const ADD_GIFT_CARD_GENERAL_CODE_FAILURE =
  "ADD_GIFT_CARD_GENERAL_CODE_FAILURE";

export const VIEW_GIFT_CARD_GENERAL = "VIEW_GIFT_CARD_GENERAL";

export const EXPORT_GIFT_CARD_GENERAL_REQUEST =
  "EXPORT_GIFT_CARD_GENERAL_REQUEST";
export const EXPORT_GIFT_CARD_GENERAL_SUCCESS =
  "EXPORT_GIFT_CARD_GENERAL_SUCCESS";
export const EXPORT_GIFT_CARD_GENERAL_FAILURE =
  "EXPORT_GIFT_CARD_GENERAL_FAILURE";

export const GET_CODE_LOG_REQUEST = "GET_CODE_LOG_REQUEST";
export const GET_CODE_LOG_SUCCESS = "GET_CODE_LOG_SUCCESS";
export const GET_CODE_LOG_FAILURE = "GET_CODE_LOG_FAILURE";

export const VIEW_TEMPLATE = "VIEW_TEMPLATE";

export const UPDATE_TEMPLATE_REQUEST = "UPDATE_TEMPLATE_REQUEST";
export const UPDATE_TEMPLATE_SUCCESS = "UPDATE_TEMPLATE_SUCCESS";
export const UPDATE_TEMPLATE_FAILURE = "UPDATE_TEMPLATE_FAILURE";

export const ARCHIVE_TEMPLATE_REQUEST = "ARCHIVE_TEMPLATE_REQUEST";
export const ARCHIVE_TEMPLATE_SUCCESS = "ARCHIVE_TEMPLATE_SUCCESS";
export const ARCHIVE_TEMPLATE_FAILURE = "ARCHIVE_TEMPLATE_FAILURE";

export const RESTORE_TEMPLATE_REQUEST = "RESTORE_TEMPLATE_REQUEST";
export const RESTORE_TEMPLATE_SUCCESS = "RESTORE_TEMPLATE_SUCCESS";
export const RESTORE_TEMPLATE_FAILURE = "RESTORE_TEMPLATE_FAILURE";

export const ADD_TEMPLATE_REQUEST = "ADD_TEMPLATE_REQUEST";
export const ADD_TEMPLATE_SUCCESS = "ADD_TEMPLATE_SUCCESS";
export const ADD_TEMPLATE_FAILURE = "ADD_TEMPLATE_FAILURE";

export const GET_ALL_TEMPLATE_REQUEST = "GET_ALL_TEMPLATE_REQUEST";
export const GET_ALL_TEMPLATE_SUCCESS = "GET_ALL_TEMPLATE_SUCCESS";
export const GET_ALL_TEMPLATE_FAILURE = "GET_ALL_TEMPLATE_FAILURE";

export const ADD_GENERATION_REQUEST = "ADD_GENERATION_REQUEST";
export const ADD_GENERATION_SUCCESS = "ADD_GENERATION_SUCCESS";
export const ADD_GENERATION_FAILURE = "ADD_GENERATION_FAILURE";
