export const GET_INVOICE_LIST = "GET_INVOICE_LIST";
export const SET_INVOICE_LIST = "SET_INVOICE_LIST";

export const GET_INVOICE_DETAIL = "GET_INVOICE_DETAIL";
export const SET_INVOICE_DETAIL = "SET_INVOICE_DETAIL";

export const LOADING_INVOICE = "LOADING_INVOICE";
export const STOP_LOADING_INVOICE = "STOP_LOADING_INVOICE";

export const LOADING_INVOICE_DETAIL = "LOADING_INVOICE_DETAIL";
export const STOP_LOADING_INVOICE_DETAIL = "STOP_LOADING_INVOICE_DETAIL";

export const LOADING_REFUND_INVOICE = "LOADING_REFUND_INVOICE";
export const STOP_LOADING_REFUND_INVOICE = "STOP_LOADING_REFUND_INVOICE";