export const ADD_MARKET_PLACE_REQUEST = "ADD_MARKET_PLACE_REQUEST";
export const ADD_MARKET_PLACE_SUCCESS = "ADD_MARKET_PLACE_SUCCESS";
export const ADD_MARKET_PLACE_FAILURE = "ADD_MARKET_PLACE_FAILURE";

export const EDIT_MARKET_PLACE_REQUEST = "EDIT_MARKET_PLACE_REQUEST";
export const EDIT_MARKET_PLACE_SUCCESS = "EDIT_MARKET_PLACE_SUCCESS";
export const EDIT_MARKET_PLACE_FAILURE = "EDIT_MARKET_PLACE_FAILURE";

export const RESTORE_MARKET_PLACE_REQUEST = "RESTORE_MARKET_PLACE_REQUEST";
export const RESTORE_MARKET_PLACE_SUCCESS = "RESTORE_MARKET_PLACE_SUCCESS";
export const RESTORE_MARKET_PLACE_FAILURE = "RESTORE_MARKET_PLACE_FAILURE";

export const ARCHIVE_MARKET_PLACE_REQUEST = "ARCHIVE_MARKET_PLACE_REQUEST";
export const ARCHIVE_MARKET_PLACE_SUCCESS = "ARCHIVE_MARKET_PLACE_SUCCESS";
export const ARCHIVE_MARKET_PLACE_FAILURE = "ARCHIVE_MARKET_PLACE_FAILURE";

export const MARKET_PLACE_INFO = "MARKET_PLACE_INFO";
