export const VIEW_STAFF = "VIEW_STAFF";
export const UPDATE_STAFF = "UPDATE_STAFF";
export const UPDATE_STAFF_SUCCESS = "UPDATE_STAFF_SUCCESS";

export const MERCHANT_UPDATE_SETTING = "MERCHANT_UPDATE_SETTING";
export const MERCHANT_UPDATE_SETTING_SUCCESS =
  "MERCHANT_UPDATE_SETTING_SUCCESS";
export const MERCHANT_UPDATE_SETTING_FAILURE =
  "MERCHANT_UPDATE_SETTING_FAILURE";

// New Constants
export const MERCHANT_ADD_TEMPLATE_REQUEST = "MERCHANT_ADD_TEMPLATE_REQUEST";
export const MERCHANT_ADD_TEMPLATE_SUCCESS = "MERCHANT_ADD_TEMPLATE_SUCCESS";
export const MERCHANT_ADD_TEMPLATE_FAIL = "MERCHANT_ADD_TEMPLATE_FAIL";

export const MERCHANT_DOWNLOAD_TEMPLATE_REQUEST =
  "MERCHANT_DOWNLOAD_TEMPLATE_REQUEST";
export const MERCHANT_DOWNLOAD_TEMPLATE_SUCCESS =
  "MERCHANT_DOWNLOAD_TEMPLATE_SUCCESS";
export const MERCHANT_DOWNLOAD_TEMPLATE_FAIL =
  "MERCHANT_DOWNLOAD_TEMPLATE_FAIL";
export const MERCHANT_DOWNLOAD_TEMPLATE_RESET =
  "MERCHANT_DOWNLOAD_TEMPLATE_RESET";

export const RESTORE_STAFF_REQUEST = "RESTORE_STAFF_REQUEST";
export const RESTORE_STAFF_SUCCESS = "RESTORE_STAFF_SUCCESS";
export const RESTORE_STAFF_FAILURE = "RESTORE_STAFF_FAILURE";

export const ARCHIVE_STAFF_REQUEST = "ARCHIVE_STAFF_REQUEST";
export const ARCHIVE_STAFF_SUCCESS = "ARCHIVE_STAFF_SUCCESS";
export const ARCHIVE_STAFF_FAILURE = "ARCHIVE_STAFF_FAILURE";

export const GET_STAFF_REQUEST = "GET_STAFF_REQUEST";
export const GET_STAFF_SUCCESS = "GET_STAFF_SUCCESS";
export const GET_STAFF_FAILURE = "GET_STAFF_FAILURE";

export const GET_STAFF_BY_ID_REQUEST = "GET_STAFF_BY_ID_REQUEST";
export const GET_STAFF_BY_ID_SUCCESS = "GET_STAFF_BY_ID_SUCCESS";
export const GET_STAFF_BY_ID_FAILURE = "GET_STAFF_BY_ID_FAILURE";

export const UPDATE_STAFF_BY_ID_REQUEST = "UPDATE_STAFF_BY_ID_REQUEST";
export const UPDATE_STAFF_BY_ID_SUCCESS = "UPDATE_STAFF_BY_ID_SUCCESS";
export const UPDATE_STAFF_BY_ID_FAILURE = "UPDATE_STAFF_BY_ID_FAILURE";

export const GET_MERCHANT_BY_ID_REQUEST = "GET_MERCHANT_BY_ID_REQUEST";
export const GET_MERCHANT_BY_ID_SUCCESS = "GET_MERCHANT_BY_ID_SUCCESS";
export const GET_MERCHANT_BY_ID_FAILURE = "GET_MERCHANT_BY_ID_FAILURE";

export const UPDATE_MERCHANT_PENDING_REQUEST =
  "UPDATE_MERCHANT_PENDING_REQUEST";
export const UPDATE_MERCHANT_PENDING_SUCCESS =
  "UPDATE_MERCHANT_PENDING_SUCCESS";
export const UPDATE_MERCHANT_PENDING_FAILURE =
  "UPDATE_MERCHANT_PENDING_FAILURE";

export const REVERT_MERCHANT_REQUEST = "REVERT_MERCHANT_REQUEST";
export const REVERT_MERCHANT_SUCCESS = "REVERT_MERCHANT_SUCCESS";
export const REVERT_MERCHANT_FAILURE = "REVERT_MERCHANT_FAILURE";

export const DELETE_MERCHANT_REQUEST = "DELETE_MERCHANT_REQUEST";
export const DELETE_MERCHANT_SUCCESS = "DELETE_MERCHANT_SUCCESS";
export const DELETE_MERCHANT_FAILURE = "DELETE_MERCHANT_FAILURE";

export const UPDATE_MERCHANT_GENERAL_REQUEST =
  "UPDATE_MERCHANT_GENERAL_REQUEST";
export const UPDATE_MERCHANT_GENERAL_SUCCESS =
  "UPDATE_MERCHANT_GENERAL_SUCCESS";
export const UPDATE_MERCHANT_GENERAL_FAILURE =
  "UPDATE_MERCHANT_GENERAL_FAILURE";

export const UPDATE_MERCHANT_BANK_REQUEST = "UPDATE_MERCHANT_BANK_REQUEST";
export const UPDATE_MERCHANT_BANK_SUCCESS = "UPDATE_MERCHANT_BANK_SUCCESS";
export const UPDATE_MERCHANT_BANK_FAILURE = "UPDATE_MERCHANT_BANK_FAILURE";

export const VIEW_MERCHANT_PRINCIPAL = "VIEW_MERCHANT_PRINCIPAL";
export const UPDATE_MERCHANT_PRINCIPAL_REQUEST =
  "UPDATE_MERCHANT_PRINCIPAL_REQUEST";
export const UPDATE_MERCHANT_PRINCIPAL_SUCCESS =
  "UPDATE_MERCHANT_PRINCIPAL_SUCCESS";
export const UPDATE_MERCHANT_PRINCIPAL_FAILURE =
  "UPDATE_MERCHANT_PRINCIPAL_FAILURE";

export const GET_MERCHANT_CATEGORY_REQUEST = "GET_MERCHANT_CATEGORY_REQUEST";
export const GET_MERCHANT_CATEGORY_SUCCESS = "GET_MERCHANT_CATEGORY_SUCCESS";
export const GET_MERCHANT_CATEGORY_FAILURE = "GET_MERCHANT_CATEGORY_FAILURE";

export const VIEW_MERCHANT_CATEGORY = "VIEW_MERCHANT_CATEGORY";

export const UPDATE_MERCHANT_CATEGORY_REQUEST =
  "UPDATE_MERCHANT_CATEGORY_REQUEST";
export const UPDATE_MERCHANT_CATEGORY_SUCCESS =
  "UPDATE_MERCHANT_CATEGORY_SUCCESS";
export const UPDATE_MERCHANT_CATEGORY_FAILURE =
  "UPDATE_MERCHANT_CATEGORY_FAILURE";

export const ADD_MERCHANT_CATEGORY_REQUEST = "ADD_MERCHANT_CATEGORY_REQUEST";
export const ADD_MERCHANT_CATEGORY_SUCCESS = "ADD_MERCHANT_CATEGORY_SUCCESS";
export const ADD_MERCHANT_CATEGORY_FAILURE = "ADD_MERCHANT_CATEGORY_FAILURE";

export const ARCHIVE_MERCHANT_CATEGORY_REQUEST =
  "ARCHIVE_MERCHANT_CATEGORY_REQUEST";
export const ARCHIVE_MERCHANT_CATEGORY_SUCCESS =
  "ARCHIVE_MERCHANT_CATEGORY_SUCCESS";
export const ARCHIVE_MERCHANT_CATEGORY_FAILURE =
  "ARCHIVE_MERCHANT_CATEGORY_FAILURE";

export const RESTORE_MERCHANT_CATEGORY_REQUEST =
  "RESTORE_MERCHANT_CATEGORY_REQUEST";
export const RESTORE_MERCHANT_CATEGORY_SUCCESS =
  "RESTORE_MERCHANT_CATEGORY_SUCCESS";
export const RESTORE_MERCHANT_CATEGORY_FAILURE =
  "RESTORE_MERCHANT_CATEGORY_FAILURE";

export const GET_MERCHANT_SERVICE_REQUEST = "GET_MERCHANT_SERVICE_REQUEST";
export const GET_MERCHANT_SERVICE_SUCCESS = "GET_MERCHANT_SERVICE_SUCCESS";
export const GET_MERCHANT_SERVICE_FAILURE = "GET_MERCHANT_SERVICE_FAILURE";

export const ADD_MERCHANT_SERVICE_REQUEST = "ADD_MERCHANT_SERVICE_REQUEST";
export const ADD_MERCHANT_SERVICE_SUCCESS = "ADD_MERCHANT_SERVICE_SUCCESS";
export const ADD_MERCHANT_SERVICE_FAILURE = "ADD_MERCHANT_SERVICE_FAILURE";

export const VIEW_MERCHANT_SERVICE = "VIEW_MERCHANT_SERVICE";

export const UPDATE_MERCHANT_SERVICE_REQUEST =
  "UPDATE_MERCHANT_SERVICE_REQUEST";
export const UPDATE_MERCHANT_SERVICE_SUCCESS =
  "UPDATE_MERCHANT_SERVICE_SUCCESS";
export const UPDATE_MERCHANT_SERVICE_FAILURE =
  "UPDATE_MERCHANT_SERVICE_FAILURE";

export const ARCHIVE_MERCHANT_SERVICE_REQUEST =
  "ARCHIVE_MERCHANT_CATEGORY_REQUEST";
export const ARCHIVE_MERCHANT_SERVICE_SUCCESS =
  "ARCHIVE_MERCHANT_CATEGORY_SUCCESS";
export const ARCHIVE_MERCHANT_SERVICE_FAILURE =
  "ARCHIVE_MERCHANT_CATEGORY_FAILURE";

export const RESTORE_MERCHANT_SERVICE_REQUEST =
  "RESTORE_MERCHANT_CATEGORY_REQUEST";
export const RESTORE_MERCHANT_SERVICE_SUCCESS =
  "RESTORE_MERCHANT_CATEGORY_SUCCESS";
export const RESTORE_MERCHANT_SERVICE_FAILURE =
  "RESTORE_MERCHANT_CATEGORY_FAILURE";

export const GET_MERCHANT_PRODUCT_REQUEST = "GET_MERCHANT_PRODUCT_REQUEST";
export const GET_MERCHANT_PRODUCT_SUCCESS = "GET_MERCHANT_PRODUCT_SUCCESS";
export const GET_MERCHANT_PRODUCT_FAILURE = "GET_MERCHANT_PRODUCT_FAILURE";

export const ADD_MERCHANT_PRODUCT_REQUEST = "ADD_MERCHANT_PRODUCT_REQUEST";
export const ADD_MERCHANT_PRODUCT_SUCCESS = "ADD_MERCHANT_PRODUCT_SUCCESS";
export const ADD_MERCHANT_PRODUCT_FAILURE = "ADD_MERCHANT_PRODUCT_FAILURE";

export const VIEW_MERCHANT_PRODUCT = "VIEW_MERCHANT_PRODUCT";

export const UPDATE_MERCHANT_PRODUCT_REQUEST =
  "UPDATE_MERCHANT_PRODUCT_REQUEST";
export const UPDATE_MERCHANT_PRODUCT_SUCCESS =
  "UPDATE_MERCHANT_PRODUCT_SUCCESS";
export const UPDATE_MERCHANT_PRODUCT_FAILURE =
  "UPDATE_MERCHANT_PRODUCT_FAILURE";

export const ARCHIVE_MERCHANT_PRODUCT_REQUEST =
  "ARCHIVE_MERCHANT_PRODUCT_REQUEST";
export const ARCHIVE_MERCHANT_PRODUCT_SUCCESS =
  "ARCHIVE_MERCHANT_PRODUCT_SUCCESS";
export const ARCHIVE_MERCHANT_PRODUCT_FAILURE =
  "ARCHIVE_MERCHANT_PRODUCT_FAILURE";

export const RESTORE_MERCHANT_PRODUCT_REQUEST =
  "RESTORE_MERCHANT_PRODUCT_REQUEST";
export const RESTORE_MERCHANT_PRODUCT_SUCCESS =
  "RESTORE_MERCHANT_PRODUCT_SUCCESS";
export const RESTORE_MERCHANT_PRODUCT_FAILURE =
  "RESTORE_MERCHANT_PRODUCT_FAILURE";

export const GET_MERCHANT_EXTRA_REQUEST = "GET_MERCHANT_EXTRA_REQUEST";
export const GET_MERCHANT_EXTRA_SUCCESS = "GET_MERCHANT_EXTRA_SUCCESS";
export const GET_MERCHANT_EXTRA_FAILURE = "GET_MERCHANT_EXTRA_FAILURE";

export const RESTORE_MERCHANT_EXTRA_REQUEST = "RESTORE_MERCHANT_EXTRA_REQUEST";
export const RESTORE_MERCHANT_EXTRA_SUCCESS = "RESTORE_MERCHANT_EXTRA_SUCCESS";
export const RESTORE_MERCHANT_EXTRA_FAILURE = "RESTORE_MERCHANT_EXTRA_FAILURE";

export const ARCHIVE_MERCHANT_EXTRA_REQUEST = " ARCHIVE_MERCHANT_EXTRA_REQUEST";
export const ARCHIVE_MERCHANT_EXTRA_SUCCESS = " ARCHIVE_MERCHANT_EXTRA_SUCCESS";
export const ARCHIVE_MERCHANT_EXTRA_FAILURE = " ARCHIVE_MERCHANT_EXTRA_FAILURE";

export const UPDATE_MERCHANT_EXTRA_REQUEST = "UPDATE_MERCHANT_EXTRA_REQUEST";
export const UPDATE_MERCHANT_EXTRA_SUCCESS = "UPDATE_MERCHANT_EXTRA_SUCCESS";
export const UPDATE_MERCHANT_EXTRA_FAILURE = "UPDATE_MERCHANT_EXTRA_FAILURE";

export const ARCHIVE_MERCHANT_REQUEST = "ARCHIVE_MERCHANT_REQUEST";
export const ARCHIVE_MERCHANT_SUCCESS = "ARCHIVE_MERCHANT_SUCCESS";
export const ARCHIVE_MERCHANT_FAILURE = "ARCHIVE_MERCHANT_FAILURE";

export const RESTORE_MERCHANT_REQUEST = "RESTORE_MERCHANT_REQUEST";
export const RESTORE_MERCHANT_SUCCESS = "RESTORE_MERCHANT_SUCCESS";
export const RESTORE_MERCHANT_FAILURE = "RESTORE_MERCHANT_FAILURE";

export const UPDATE_MERCHANT_SETTING_REQUEST =
  "UPDATE_MERCHANT_SETTING_REQUEST";
export const UPDATE_MERCHANT_SETTING_SUCCESS =
  "UPDATE_MERCHANT_SETTING_SUCCESS";
export const UPDATE_MERCHANT_SETTING_FAILURE =
  "UPDATE_MERCHANT_SETTING_FAILURE";

export const ADD_STAFF_REQUEST = "ADD_STAFF_REQUEST";
export const ADD_STAFF_SUCCESS = "ADD_STAFF_SUCCESS";
export const ADD_STAFF_FAILURE = "ADD_STAFF_FAILURE";

export const GET_MERCHANT_ACTIVITY_REQUEST = "GET_MERCHANT_ACTIVITY_REQUEST";
export const GET_MERCHANT_ACTIVITY_SUCCESS = "GET_MERCHANT_ACTIVITY_SUCCESS";
export const GET_MERCHANT_ACTIVITY_FAILURE = "GET_MERCHANT_ACTIVITY_FAILURE";

export const ADD_MERCHANT_REQUEST = "ADD_MERCHANT_REQUEST";
export const ADD_MERCHANT_SUCCESS = "ADD_MERCHANT_SUCCESS ";
export const ADD_MERCHANT_FAILURE = "ADD_MERCHANT_FAILURE";

export const SET_PENDING_STATUS_REQUEST = "SET_PENDING_STATUS_REQUEST";
export const SET_PENDING_STATUS_SUCCESS = "SET_PENDING_STATUS_SUCCESS";
export const SET_PENDING_STATUS_FAILURE = "SET_PENDING_STATUS_FAILURE";

export const APPROVE_MERCHANT_REQUEST = "APPROVE_MERCHANT_REQUEST";
export const APPROVE_MERCHANT_SUCCESS = "APPROVE_MERCHANT_SUCCESS";
export const APPROVE_MERCHANT_FAILURE = "APPROVE_MERCHANT_FAILURE";

export const REJECT_MERCHANT_REQUEST = "REJECT_MERCHANT_REQUEST";
export const REJECT_MERCHANT_SUCCESS = "REJECT_MERCHANT_SUCCESS";
export const REJECT_MERCHANT_FAILURE = "REJECT_MERCHANT_FAILURE";
