export const VIEW_PROFILE_MERCHANT = "VIEW_PROFILE_MERCHANT";

export const UPDATE_MERCHANT = "UPDATE_MERCHANT";
export const UPDATE_MERCHANT_SUCCESS = "UPDATE_MERCHANT_SUCCESS";
export const UPDATE_MERCHANT_ERROR = "UPDATE_MERCHANT_ERROR";

export const MERCHANT_APPROVAL = "MERCHANT_APPROVAL";
export const MERCHANT_APPROVAL_SUCCESS = "MERCHANT_APPROVAL_SUCCESS";
export const MERCHANT_APPROVAL_ERROR = "MERCHANT_APPROVAL_ERROR";

export const MERCHANT_REJECT = "MERCHANT_REJECT";
export const MERCHANT_REJECT_SUCCESS = "MERCHANT_REJECT_SUCCESS";
export const MERCHANT_REJECT_ERROR = "MERCHANT_REJECT_ERROR";

export const VIEW_PRINCIPAL = "VIEW_PRINCIPAL";
export const UPDATE_MERCHANT_PRINCIPAL = "UPDATE_MERCHANT_PRINCIPAL";
export const UPDATE_MERCHANT_PRINCIPAL_SUCCESS =
  "UPDATE_MERCHANT_PRINCIPAL_SUCCESS";
export const UPDATE_MERCHANT_PRINCIPAL_FAILURE =
  "UPDATE_MERCHANT_PRINCIPAL_FAILURE";

export const DELETE_MERCHANT = "DELETE_MERCHANT";
export const DELETE_MERCHANT_SUCCESS = "DELETE_MERCHANT_SUCCESS";
export const DELETE_MERCHANT_ERROR = "DELETE_MERCHANT_ERROR";

export const GET_MERCHANT_BY_ID = "GET_MERCHANT_BY_ID";
export const GET_MERCHANT_BY_ID_SUCCESS = "GET_MERCHANT_BY_ID_SUCCESS";
export const GET_MERCHANT_BY_ID_FAILURE = "GET_MERCHANT_BY_ID_FAILURE";

export const VIEW_SERVICE = "VIEW_SERVICE";
export const UPDATE_MERCHANT_SERVICE = "UPDATE_MERCHANT_SERVICE";
export const UPDATE_MERCHANT_SERVICE_SUCCESS =
  "UPDATE_MERCHANT_SERVICE_SUCCESS";
export const UPDATE_MERCHANT_SERVICE_FAILURE =
  "UPDATE_MERCHANT_SERVICE_FAILURE";

export const ADD_STAFF = "ADD_STAFF";
export const ADD_STAFF_SUCCESS = "ADD_STAFF_SUCCESS";
export const ADD_STAFF_FAILURE = "ADD_STAFF_FAILURE";

export const VIEW_STAFF = "VIEW_STAFF";
export const UPDATE_STAFF = "UPDATE_STAFF";
export const UPDATE_STAFF_SUCCESS = "UPDATE_STAFF_SUCCESS";

export const ARCHIVE_MERCHANT = "ARCHIVE_MERCHANT";
export const RESTORE_MERCHANT = "RESTORE_MERCHANT";

export const SET_PENDING_STATUS = "SET_PENDING_STATUS";
export const SET_PENDING_STATUS_SUCCESS = "SET_PENDING_STATUS_SUCCESS";
export const SET_PENDING_STATUS_FAILURE = "SET_PENDING_STATUS_FAILURE";

export const MERCHANT_UPDATE_SETTING = "MERCHANT_UPDATE_SETTING";
export const MERCHANT_UPDATE_SETTING_SUCCESS =
  "MERCHANT_UPDATE_SETTING_SUCCESS";
export const MERCHANT_UPDATE_SETTING_FAILURE =
  "MERCHANT_UPDATE_SETTING_FAILURE";

export const ADD_MERCHANT = "ADD_MERCHANT";
export const ADD_MERCHANT_SUCCESS = "ADD_MERCHANT_SUCCESS ";
export const ADD_MERCHANT_FAILURE = "ADD_MERCHANT_FAILURE";

export const UPDATE_MERCHANT_BANK = "UPDATE_MERCHANT_BANK";
export const UPDATE_MERCHANT_BANK_SUCCESS = "UPDATE_MERCHANT_BANK_SUCCESS ";
export const UPDATE_MERCHANT_BANK_FAILURE = "UPDATE_MERCHANT_BANK_FAILURE";

export const GET_MERCHANT_EXTRA = "GET_MERCHANT_EXTRA";
export const GET_MERCHANT_EXTRA_SUCCESS = "GET_MERCHANT_EXTRA_SUCCESS";
export const ARCHIVE_MERCHANT_EXTRA = "ARCHIVE_MERCHANT_EXTRA";

export const RESTORE_MERCHANT_EXTRA = "RESTORE_MERCHANT_EXTRA";
export const UPDATE_MERCHANT_EXTRA = "UPDATE_MERCHANT_EXTRA";

// New Constants
export const MERCHANT_ADD_TEMPLATE_REQUEST = "MERCHANT_ADD_TEMPLATE_REQUEST";
export const MERCHANT_ADD_TEMPLATE_SUCCESS = "MERCHANT_ADD_TEMPLATE_SUCCESS";
export const MERCHANT_ADD_TEMPLATE_FAIL = "MERCHANT_ADD_TEMPLATE_FAIL";

export const MERCHANT_DOWNLOAD_TEMPLATE_REQUEST =
  "MERCHANT_DOWNLOAD_TEMPLATE_REQUEST";
export const MERCHANT_DOWNLOAD_TEMPLATE_SUCCESS =
  "MERCHANT_DOWNLOAD_TEMPLATE_SUCCESS";
export const MERCHANT_DOWNLOAD_TEMPLATE_FAIL =
  "MERCHANT_DOWNLOAD_TEMPLATE_FAIL";
export const MERCHANT_DOWNLOAD_TEMPLATE_RESET =
  "MERCHANT_DOWNLOAD_TEMPLATE_RESET";

export const RESTORE_STAFF_REQUEST = "RESTORE_STAFF_REQUEST";
export const RESTORE_STAFF_SUCCESS = "RESTORE_STAFF_SUCCESS";
export const RESTORE_STAFF_FAILURE = "RESTORE_STAFF_FAILURE";

export const ARCHIVE_STAFF_REQUEST = "ARCHIVE_STAFF_REQUEST";
export const ARCHIVE_STAFF_SUCCESS = "ARCHIVE_STAFF_SUCCESS";
export const ARCHIVE_STAFF_FAILURE = "ARCHIVE_STAFF_FAILURE";

export const GET_STAFF_REQUEST = "GET_STAFF_REQUEST";
export const GET_STAFF_SUCCESS = "GET_STAFF_SUCCESS";
export const GET_STAFF_FAILURE = "GET_STAFF_FAILURE";

export const GET_STAFF_BY_ID_REQUEST = "GET_STAFF_BY_ID_REQUEST";
export const GET_STAFF_BY_ID_SUCCESS = "GET_STAFF_BY_ID_SUCCESS";
export const GET_STAFF_BY_ID_FAILURE = "GET_STAFF_BY_ID_FAILURE";

export const UPDATE_STAFF_BY_ID_REQUEST = "UPDATE_STAFF_BY_ID_REQUEST";
export const UPDATE_STAFF_BY_ID_SUCCESS = "UPDATE_STAFF_BY_ID_SUCCESS";
export const UPDATE_STAFF_BY_ID_FAILURE = "UPDATE_STAFF_BY_ID_FAILURE";
