export const GET_TICKET_BY_ID_REQUEST = "GET_TICKET_BY_ID_REQUEST";
export const GET_TICKET_BY_ID_SUCCESS = "GET_TICKET_BY_ID_SUCCESS";
export const GET_TICKET_BY_ID_FAILURE = "GET_TICKET_BY_ID_FAILURE";

export const ADD_TICKET_REQUEST = "ADD_TICKET_REQUEST";
export const ADD_TICKET_SUCCESS = "ADD_TICKET_SUCCESS";
export const ADD_TICKET_FAILURE = "ADD_TICKET_FAILURE";

export const UPDATE_TICKET_REQUEST = "UPDATE_TICKET_REQUEST";
export const UPDATE_TICKET_SUCCESS = "UPDATE_TICKET_SUCCESS";
export const UPDATE_TICKET_FAILURES = "UPDATE_TICKET_FAILURES";
