export const GET_TICKET_BY_ID_REQUEST = "GET_TICKET_BY_ID_REQUEST";
export const GET_TICKET_BY_ID_SUCCESS = "GET_TICKET_BY_ID_SUCCESS";
export const GET_TICKET_BY_ID_FAILURE = "GET_TICKET_BY_ID_FAILURE";

export const GET_TICKET_COMMENT_REQUEST = "GET_TICKET_COMMENT_REQUEST";
export const GET_TICKET_COMMENT_SUCCESS = "GET_TICKET_COMMENT_SUCCESS";
export const GET_TICKET_COMMENT_FAILURE = "GET_TICKET_COMMENT_FAILURE";

export const GET_TICKET_LOG_REQUEST = "GET_TICKET_LOG_REQUEST";
export const GET_TICKET_LOG_SUCCESS = "GEt_TICKET_LOG_SUCCESS";
export const GET_TICKET_LOG_FAILURE = "GEt_TICKET_LOG_FAILURE";

export const ADD_TICKET_REQUEST = "ADD_TICKET_REQUEST";
export const ADD_TICKET_SUCCESS = "ADD_TICKET_SUCCESS";
export const ADD_TICKET_FAILURE = "ADD_TICKET_FAILURE";

export const ADD_TICKET_FILE_REQUEST = "ADD_TICKET_FILE_REQUEST";
export const ADD_TICKET_FILE_SUCCESS = "ADD_TICKET_FILE_SUCCESS";
export const ADD_TICKET_FILE_FAILURE = "ADD_TICKET_FILE_FAILURE";

export const SEND_COMMENT_REQUEST = "SEND_COMMENT_REQUEST";
export const SEND_COMMENT_SUCCESS = "SEND_COMMENT_SUCCESS";
export const SEND_COMMENT_FAILURE = "SEND_COMMENT_FAILURE";

export const UPDATE_TICKET_REQUEST = "UPDATE_TICKET_REQUEST";
export const UPDATE_TICKET_SUCCESS = "UPDATE_TICKET_SUCCESS";
export const UPDATE_TICKET_FAILURES = "UPDATE_TICKET_FAILURES";

export const DELETE_TICKET_FILE_REQUEST = "DELETE_TICKET_FILE_REQUEST";
export const DELETE_TICKET_FILE_SUCCESS = "DELETE_TICKET_FILE_SUCCESS";
export const DELETE_TICKET_FILE_FAILURE = "DELETE_TICKET_FILE_FAILURE";
