export const GET_USER_BY_ID_REQUEST = "GET_USER_BY_ID_REQUEST";
export const GET_USER_BY_ID_SUCCESS = "GET_USER_BY_ID_SUCCESS";
export const GET_USER_BY_ID_FAILURE = "GET_USER_BY_ID_FAILURE";

export const ARCHIVE_USER_BY_ID_REQUEST = "ARCHIVE_USER_BY_ID_REQUEST";
export const ARCHIVE_USER_BY_ID_SUCCESS = "ARCHIVE_USER_BY_ID_SUCCESS";
export const ARCHIVE_USER_BY_ID_FAILURE = "ARCHIVE_USER_BY_ID_FAILURE";

export const RESTORE_USER_BY_ID_REQUEST = " RESTORE_USER_BY_ID_REQUEST";
export const RESTORE_USER_BY_ID_SUCCESS = " RESTORE_USER_BY_ID_SUCCESS";
export const RESTORE_USER_BY_ID_FAILURE = " RESTORE_USER_BY_ID_FAILURE";

export const UPDATE_USER_ADMIN_REQUEST = "UPDATE_USER_ADMIN_REQUEST";
export const UPDATE_USER_ADMIN_SUCCESS = "UPDATE_USER_ADMIN_SUCCESS";
export const UPDATE_USER_ADMIN_FAILURE = "UPDATE_USER_ADMIN_FAILURE";

export const UPDATE_USER_PASSWORD_REQUEST = "UPDATE_USER_PASSWORD_REQUEST";
export const UPDATE_USER_PASSWORD_SUCCESS = "UPDATE_USER_PASSWORD_SUCCESS";
export const UPDATE_USER_PASSWORD_FAILURE = "UPDATE_USER_PASSWORD_FAILURE";

export const ADD_USER_REQUEST = "ADD_USER_REQUEST";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAILURE = "ADD_USER_FAILURE";
