// Get consumer by ID
export const GET_CONSUMER_BY_ID = "GET_CONSUMER_BY_ID";
export const GET_CONSUMER_BY_ID_SUCCESS = "GET_CONSUMER_BY_ID_SUCCESS";
export const GET_CONSUMER_BY_ID_FAILURE = "GET_CONSUMER_BY_ID_FAILURE";
// View consumer
export const VIEW_CONSUMER = "VIEW_CONSUMER";
// Update consumer
export const UPDATE_CONSUMER = "UPDATE_CONSUMER";
export const UPDATE_CONSUMER_SUCCESS = "UPDATE_CONSUMER_SUCCESS";
export const UPDATE_CONSUMER_FAILURE = "UPDATE_CONSUMER_FAILURE";
// Delete consumer
export const DELETE_CONSUMER_BY_ID = "DELETE_CONSUMER_BY_ID";
export const DELETE_CONSUMER_BY_ID_SUCCESS = "DELETE_CONSUMER_BY_ID_SUCCESS";
export const DELETE_CONSUMER_BY_ID_FAILURE = "DELETE_CONSUMER_BY_ID_FAILURE";
// Restore consumer
export const RESTORE_CONSUMER_BY_ID = "RESTORE_CONSUMER_BY_ID";
export const RESTORE_CONSUMER_BY_ID_SUCCESS = "RESTORE_CONSUMER_BY_ID_SUCCESS";
export const RESTORE_CONSUMER_BY_ID_FAILURE = "RESTORE_CONSUMER_BY_ID_FAILURE";
