// LOGIN USER (ADMIN)
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const USER_LOGOUT = "USER_LOGOUT";

// VERIFY USER (ADMIN)
export const VERIFY_USER = "VERIFY_USER";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";
export const VERIFY_FAILURE = "VERIFY_FAILURE";

// GET ALL USER (ADMIN)
export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";
export const VIEW_PROFILE_USER = "VIEW_PROFILE_USER";

// Get current user
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS";
export const GET_CURRENT_USER_FAILURE = "GET_CURRENT_USER_FAILURE";

// GET ADMIN USER BY ID
export const GET_USER_BY_ID = "GET_USER_BY_ID";
export const GET_USER_BY_ID_SUCCESS = "GET_USER_BY_ID_SUCCESS";
export const GET_USER_BY_ID_FAILURE = "GET_USER_BY_ID_FAILURE";

// ADD NEW ADMIN USER
export const ADD_ADMIN = "ADD_ADMIN";
export const ADD_ADMIN_SUCCESS = "ADD_ADMIN_SUCCESS";
export const ADD_ADMIN_FAILURE = "ADD_ADMIN_FAILURE";

// GET  PERMISSION BY ROLE ID
export const GET_PERMISSION_BY_ID = "GET_PERMISSION_BY_ID";
export const GET_PERMISSION_BY_ID_SUCCESS = "GET_PERMISSION_BY_ID_SUCCESS";
export const GET_PERMISSION_BY_ID_FAILURE = "GET_PERMISSION_BY_ID_FAILURE";

// Get permission on login
export const GET_PERMISSION_ON_LOGIN = "GET_PERMISSION_ON_LOGIN";
export const GET_PERMISSION_ON_LOGIN_SUCCESS =
  "GET_PERMISSION_ON_LOGIN_SUCCESS";
// Get all permissions
export const GET_ALL_PERMISSION = "GET_ALL_PERMISSION";
export const GET_ALL_PERMISSION_SUCCESS = "GET_ALL_PERMISSION_SUCCESS";
export const GET_ALL_PERMISSION_FAILURE = "GET_ALL_PERMISSION_FAILURE";

// Update permissions by role
export const UPDATE_PERMISSIONS = "UPDATE_PERMISSIONS";
export const UPDATE_PERMISSIONS_SUCCESS = "UPDATE_PERMISSIONS_SUCCESS";
export const UPDATE_PERMISSIONS_FAILURE = "UPDATE_PERMISSIONS_FAILURE";

// Update user
export const UPDATE_USER_ADMIN = "UPDATE_USER_ADMIN";
export const UPDATE_USER_ADMIN_SUCCESS = "UPDATE_USER_ADMIN_SUCCESS";
export const UPDATE_USER_ADMIN_FAILURE = "UPDATE_USER_ADMIN_FAILURE";

// Change user password
export const UPDATE_USER_PASSWORD = "UPDATE_USER_PASSWORD";

// Enable & Disable user
export const DISABLE_USER = "DISABLE_USER";
export const ENABLE_USER = "ENABLE_USER";
