import { fork } from "redux-saga/effects";
import {
  USER_LOGIN_SAGA,
  GET_ALL_USER_SAGA,
  USER_VERIFY_SAGA,
  ADD_USER_SAGA,
  GET_USER_BY_ID_SAGA,
  GET_PERMISSION_BY_ROLE_ID_SAGA,
  GET_ALL_PERMISSION_SAGA,
  UPDATE_PERMISSION_SAGA,
  UPDATE_USER_SAGA,
  USER_LOGOUT_SAGA,
  GET_PERMISSION_ON_LOGIN_SAGA,
  GET_CURRENT_USER_SAGA,
  DISABLE_USER_SAGA,
  ENABLE_USER_SAGA,
  CHANGE_USER_PASSWORD_SAGA,
} from "../sagas/sagaFunction/user";
import {
  // GET_ALL_MERCHANT_SAGA,
  UPDATE_MERCHANT_SAGA,
  GET_MERCHANT_BY_ID_SAGA,
  // GET_ALL_REJECTED_MERCHANT_SAGA,
  // GET_ALL_MERCHANT_REQUEST_SAGA,
  MERCHANT_APPROVAL_SAGA,
  MERCHANT_REJECT_SAGA,
  DELETE_MERCHANT_SAGA,
  RESTORE_MERCHANT_SAGA,
  ARCHIVE_MERCHANT_SAGA,
  SET_PENDING_STATUS_SAGA,
  MERCHANT_UPDATE_SETTING_SAGA,
  UPDATE_MERCHANT_PRINCIPAL_SAGA,
  UPDATE_MERCHANT_SERVICE_SAGA,
  UPDATE_MERCHANT_BANK_SAGA,
  GET_MERCHANT_EXTRA_SAGA,
  ARCHIVE_MERCHANT_EXTRA_SAGA,
  RESTORE_MERCHANT_EXTRA_SAGA,
  ADD_STAFF_SAGA,
} from "../sagas/sagaFunction/merchants";

import { GET_ALL_LOG_SAGA } from "../sagas/sagaFunction/logs";
import {
  GET_ALL_QUESTION_SAGA,
  UPDATE_QUESTION_SAGA,
} from "./sagaFunction/questions";
import {
  GET_ALL_TRANSACTION_SAGA,
  GET_USER_TRANSACTION_SAGA,
  GET_USER_ACTIVITY_SAGA,
  GET_ALL_BATCH_SAGA,
  GET_P2P_TRANSACTION_SAGA,
  GET_BATCH_DETAIL_SAGA,
} from "./sagaFunction/transactions";

import { GET_APPROVED_SAGA } from "./sagaFunction/reports";

import {
  GET_GIFT_CARD_SAGA,
  GET_TEMPLATE_SAGA,
  GET_GIFT_CARD_BY_ID_SAGA,
  GET_GIFT_CARD_CODE_LOG_BY_ID_SAGA,
} from "./sagaFunction/gift-card";

import {
  GET_CONSUMER_BY_ID_SAGA,
  UPDATE_CONSUMER_SAGA,
  DELETE_CONSUMER_BY_ID_SAGA,
  RESTORE_CONSUMER_BY_ID_SAGA,
} from "./sagaFunction/Consumer";

export default function* rootSaga() {
  yield fork(USER_LOGIN_SAGA);
  // yield fork(GET_ALL_MERCHANT_SAGA);
  // yield fork(GET_ALL_MERCHANT_REQUEST_SAGA);
  yield fork(GET_ALL_USER_SAGA);
  // yield fork(GET_ALL_NOTIFICATION_SAGA);
  yield fork(GET_ALL_LOG_SAGA);
  // yield fork(GET_ALL_REJECTED_MERCHANT_SAGA);
  yield fork(GET_ALL_QUESTION_SAGA);
  yield fork(GET_ALL_TRANSACTION_SAGA);
  // yield fork(GET_ALL_USER_SAGA);
  yield fork(GET_USER_TRANSACTION_SAGA);
  yield fork(GET_USER_ACTIVITY_SAGA);
  yield fork(UPDATE_MERCHANT_SAGA);
  yield fork(GET_MERCHANT_BY_ID_SAGA);
  yield fork(MERCHANT_APPROVAL_SAGA);
  yield fork(MERCHANT_REJECT_SAGA);
  yield fork(USER_VERIFY_SAGA);
  yield fork(UPDATE_QUESTION_SAGA);
  yield fork(GET_APPROVED_SAGA);
  yield fork(ADD_USER_SAGA);
  yield fork(GET_USER_BY_ID_SAGA);
  yield fork(GET_ALL_BATCH_SAGA);
  yield fork(GET_P2P_TRANSACTION_SAGA);
  yield fork(GET_BATCH_DETAIL_SAGA);
  yield fork(GET_GIFT_CARD_SAGA);
  yield fork(GET_TEMPLATE_SAGA);
  yield fork(GET_GIFT_CARD_BY_ID_SAGA);
  yield fork(GET_GIFT_CARD_CODE_LOG_BY_ID_SAGA);
  yield fork(GET_PERMISSION_BY_ROLE_ID_SAGA);
  yield fork(GET_ALL_PERMISSION_SAGA);
  yield fork(UPDATE_PERMISSION_SAGA);
  yield fork(DELETE_MERCHANT_SAGA);
  yield fork(GET_CONSUMER_BY_ID_SAGA);
  yield fork(UPDATE_CONSUMER_SAGA);
  yield fork(RESTORE_CONSUMER_BY_ID_SAGA);
  yield fork(DELETE_CONSUMER_BY_ID_SAGA);
  yield fork(UPDATE_USER_SAGA);
  yield fork(USER_LOGOUT_SAGA);
  yield fork(GET_PERMISSION_ON_LOGIN_SAGA);
  yield fork(GET_CURRENT_USER_SAGA);
  yield fork(DISABLE_USER_SAGA);
  yield fork(ENABLE_USER_SAGA);
  yield fork(CHANGE_USER_PASSWORD_SAGA);
  yield fork(RESTORE_MERCHANT_SAGA);
  yield fork(ARCHIVE_MERCHANT_SAGA);
  yield fork(SET_PENDING_STATUS_SAGA);
  yield fork(MERCHANT_UPDATE_SETTING_SAGA);
  yield fork(UPDATE_MERCHANT_PRINCIPAL_SAGA);
  yield fork(UPDATE_MERCHANT_SERVICE_SAGA);
  yield fork(UPDATE_MERCHANT_BANK_SAGA);
  yield fork(GET_MERCHANT_EXTRA_SAGA);
  yield fork(ARCHIVE_MERCHANT_EXTRA_SAGA);
  yield fork(RESTORE_MERCHANT_EXTRA_SAGA);
  yield fork(ADD_STAFF_SAGA);
}
