// GENERATION
export const GET_GIFTCARD = "GET_GIFTCARD";
export const GET_GIFTCARD_SUCCESS = "GET_GIFTCARD_SUCCESS";
export const GET_GIFTCARD_ERROR = "GET_GIFTCARD_ERROR";
// GET GENERATION BY ID
export const GET_GIFTCARD_BY_ID = "GET_GIFTCARD_BY_ID";
export const GET_GIFTCARD_BY_ID_SUCCESS = "GET_GIFTCARD_BY_ID_SUCCESS";
export const GET_GIFTCARD_BY_ID_ERROR = "GET_GIFTCARD_BY_ID_ERROR";
// GET GENERATION CODE LOG BY ID
export const GET_GIFTCARD_CODE_LOG_BY_ID = "GET_GIFTCARD_CODE_LOG_BY_ID";
export const GET_GIFTCARD_CODE_LOG_BY_ID_SUCCESS =
  "GET_GIFTCARD_CODE_LOG_BY_ID_SUCCESS";
export const GET_GIFTCARD_CODE_LOG_BY_ID_ERROR =
  "GET_GIFTCARD_CODE_LOG_BY_ID_ERROR";
// GENERATION NEW CODES
// export const GENERATION_CODE = "GENERATION_CODE";
// export const GENERATION_CODE_SUCCESS = "GENERATION_CODE_SUCCES";
// export const GENERATION_CODE_ERROR = "GENERATION_CODE_ERROR";
// TEMPLATE
export const GET_TEMPLATE = "GET_TEMPLATE";
export const GET_TEMPLATE_SUCCESS = "GET_TEMPLATE_SUCCESS";
export const GET_TEMPLATE_ERROR = "GET_TEMPLATE_ERROR";
// CODES

// VIEW DETAIL
export const VIEW_DETAIL = "VIEW_DETAIL";
